# Generated by Django 3.2.4 on 2021-06-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_value_message_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='text',
            new_name='value',
        ),
    ]
