# Generated by Django 3.2.4 on 2021-06-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_text_message_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='value',
            new_name='text',
        ),
    ]
